/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as SupportImport } from './routes/support'
import { Route as PromptImport } from './routes/prompt'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as IndexImport } from './routes/index'
import { Route as PromptDateImport } from './routes/prompt/$date'
import { Route as ProfileUsernameImport } from './routes/profile/$username'
import { Route as PaymentSuccessImport } from './routes/payment/success'
import { Route as PaymentCancelImport } from './routes/payment/cancel'
import { Route as DoodleIdImport } from './routes/doodle/$id'
import { Route as BadgeIdImport } from './routes/badge/$id'

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const PromptRoute = PromptImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PromptDateRoute = PromptDateImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => PromptRoute,
} as any)

const ProfileUsernameRoute = ProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRoute,
} as any)

const PaymentSuccessRoute = PaymentSuccessImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRoute,
} as any)

const PaymentCancelRoute = PaymentCancelImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRoute,
} as any)

const DoodleIdRoute = DoodleIdImport.update({
  id: '/doodle/$id',
  path: '/doodle/$id',
  getParentRoute: () => rootRoute,
} as any)

const BadgeIdRoute = BadgeIdImport.update({
  id: '/badge/$id',
  path: '/badge/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/badge/$id': {
      id: '/badge/$id'
      path: '/badge/$id'
      fullPath: '/badge/$id'
      preLoaderRoute: typeof BadgeIdImport
      parentRoute: typeof rootRoute
    }
    '/doodle/$id': {
      id: '/doodle/$id'
      path: '/doodle/$id'
      fullPath: '/doodle/$id'
      preLoaderRoute: typeof DoodleIdImport
      parentRoute: typeof rootRoute
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelImport
      parentRoute: typeof rootRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessImport
      parentRoute: typeof rootRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameImport
      parentRoute: typeof rootRoute
    }
    '/prompt/$date': {
      id: '/prompt/$date'
      path: '/$date'
      fullPath: '/prompt/$date'
      preLoaderRoute: typeof PromptDateImport
      parentRoute: typeof PromptImport
    }
  }
}

// Create and export the route tree

interface PromptRouteChildren {
  PromptDateRoute: typeof PromptDateRoute
}

const PromptRouteChildren: PromptRouteChildren = {
  PromptDateRoute: PromptDateRoute,
}

const PromptRouteWithChildren =
  PromptRoute._addFileChildren(PromptRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/doodle/$id': typeof DoodleIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/prompt/$date': typeof PromptDateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/doodle/$id': typeof DoodleIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/prompt/$date': typeof PromptDateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/prompt': typeof PromptRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/doodle/$id': typeof DoodleIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/prompt/$date': typeof PromptDateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/prompt'
    | '/support'
    | '/terms'
    | '/badge/$id'
    | '/doodle/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/profile/$username'
    | '/prompt/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/prompt'
    | '/support'
    | '/terms'
    | '/badge/$id'
    | '/doodle/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/profile/$username'
    | '/prompt/$date'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/prompt'
    | '/support'
    | '/terms'
    | '/badge/$id'
    | '/doodle/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/profile/$username'
    | '/prompt/$date'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  PromptRoute: typeof PromptRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BadgeIdRoute: typeof BadgeIdRoute
  DoodleIdRoute: typeof DoodleIdRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  PromptRoute: PromptRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BadgeIdRoute: BadgeIdRoute,
  DoodleIdRoute: DoodleIdRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privacy",
        "/prompt",
        "/support",
        "/terms",
        "/badge/$id",
        "/doodle/$id",
        "/payment/cancel",
        "/payment/success",
        "/profile/$username"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/prompt": {
      "filePath": "prompt.tsx",
      "children": [
        "/prompt/$date"
      ]
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/badge/$id": {
      "filePath": "badge/$id.tsx"
    },
    "/doodle/$id": {
      "filePath": "doodle/$id.tsx"
    },
    "/payment/cancel": {
      "filePath": "payment/cancel.tsx"
    },
    "/payment/success": {
      "filePath": "payment/success.tsx"
    },
    "/profile/$username": {
      "filePath": "profile/$username.tsx"
    },
    "/prompt/$date": {
      "filePath": "prompt/$date.tsx",
      "parent": "/prompt"
    }
  }
}
ROUTE_MANIFEST_END */
